debug reports

diff --git a/.github/workflows/ci-build-ntk-on-push-tags-e2e-tests.yaml b/.github/workflows/ci-build-ntk-on-push-tags-e2e-tests.yaml
--- a/.github/workflows/ci-build-ntk-on-push-tags-e2e-tests.yaml
+++ b/.github/workflows/ci-build-ntk-on-push-tags-e2e-tests.yaml
@@ -7,7 +7,7 @@ defaults:
     working-directory: /home/runner/work/
 
 jobs:
-   build-tests:
+  build-tests:
     name: Run Playwright Tests
     runs-on: self-hosted
     environment: ${{ inputs.environment }}
@@ -74,8 +74,8 @@ jobs:
 
       - name: Run Once
         # run: cd ./novatalks.tests/novatalks.tests/ && npx playwright test QANT-16-TimerStatus.spec.ts
-        # run: npx playwright test QANT-16-TimerStatus.spec.ts
-        run: env; npx playwright test #--grep @bug
+        run: npx playwright test QANT-16-TimerStatus.spec.ts
+        # run: env; npx playwright test #--grep @bug
         working-directory: ./
         env:
           ENV_URL: ${{ secrets.LAB_ENV_URL }}
@@ -89,12 +89,67 @@ jobs:
           API_TOKEN: ${{ secrets.LAB_API_TOKEN }}
           PLAYWRIGHT_BROWSERS_PATH: ./browsers
 
-      - uses: actions/upload-artifact@v4
+      - name: Save Artifact
+        uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
           name: playwright-report
           path: playwright-report/
           retention-days: 30
 
+  publish-report:
+    name: Publish HTML Report
+    # using always() is not ideal here, because it would also run if the workflow was cancelled
+    if: ${{ success() }}
+    needs: [build-tests]
+    runs-on: self-hosted
+    continue-on-error: true
+    env:
+      # Unique URL path for each workflow run attempt
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v4
+        with:
+          ref: gh-pages
+
+      - name: Set Git User
+        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "<>""
+
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v2
+        with:
+          name: playwright-report
+          path: ${{ env.HTML_REPORT_URL_PATH }}
+
+      - name: Push HTML Report
+        timeout-minutes: 3
+        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+        # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+      - name: Output Report URL as Worfklow Annotation
+        run: |
+          FULL_HTML_REPORT_URL=https://novaittestteam.github.io/novatalks.tests/$HTML_REPORT_URL_PATH
+
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
 
 
