full run

diff --git a/.github/workflows/ci-build-ntk-on-push-tags-build.yaml b/.github/workflows/ci-build-ntk-on-push-tags-build.yaml
--- a/.github/workflows/ci-build-ntk-on-push-tags-build.yaml
+++ b/.github/workflows/ci-build-ntk-on-push-tags-build.yaml
@@ -3,41 +3,41 @@ on:
   workflow_call:
 
 jobs:
-  # linter: 
-  #   name: Linter
-  #   runs-on: self-hosted
-  #   environment: ${{ inputs.environment }}
-  #   outputs:
-  #     LINTER_CHECK: ${{ steps.linter_res.outputs.LINTER_CHECK }} 
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
+  linter: 
+    name: Linter
+    runs-on: self-hosted
+    environment: ${{ inputs.environment }}
+    outputs:
+      LINTER_CHECK: ${{ steps.linter_res.outputs.LINTER_CHECK }} 
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
 
-  #     - name: 💿 Setup NODEJS
-  #       uses: actions/setup-node@v3
-  #       id: node_inst
-  #       with:
-  #         node-version: 18
+      - name: 💿 Setup NODEJS
+        uses: actions/setup-node@v3
+        id: node_inst
+        with:
+          node-version: 18
 
-  #     - name: ▶️ Install Node.js dependencies
-  #       run: |
-  #         npm i eslint-plugin-security
-  #         npm i @typescript-eslint/eslint-plugin
+      - name: ▶️ Install Node.js dependencies
+        run: |
+          npm i eslint-plugin-security
+          npm i @typescript-eslint/eslint-plugin
 
-  #     - name: 🇪🇸 Lint SRC
-  #       id: linter
-  #       run: npx eslint --ext .js,.vue,.ts --ignore-path .gitignore . --quiet
+      - name: 🇪🇸 Lint SRC
+        id: linter
+        run: npx eslint --ext .js,.vue,.ts --ignore-path .gitignore . --quiet
 
-  #     - name: End Linter Step
-  #       if: success() || failure()
-  #       id: linter_res
-  #       run: |
-  #         if [[ ${{ steps.linter.outcome  }} == 'success' ]];
-  #         then
-  #           echo "LINTER_CHECK=✅OK" | tee -a $GITHUB_OUTPUT
-  #         else
-  #           echo "LINTER_CHECK=❌FAILED" | tee -a $GITHUB_OUTPUT
-  #         fi
+      - name: End Linter Step
+        if: success() || failure()
+        id: linter_res
+        run: |
+          if [[ ${{ steps.linter.outcome  }} == 'success' ]];
+          then
+            echo "LINTER_CHECK=✅OK" | tee -a $GITHUB_OUTPUT
+          else
+            echo "LINTER_CHECK=❌FAILED" | tee -a $GITHUB_OUTPUT
+          fi
 
   # security:
   #   name: Security
@@ -88,6 +88,8 @@ jobs:
     name: Build Image
     runs-on: self-hosted
     environment: ${{ inputs.environment }}
+    if: always()
+    needs: [linter]
     # permissions:
     #   contents: read
     #   packages: write
@@ -168,46 +170,46 @@ jobs:
             ${{ secrets.CR_DH_USERNAME }}/${{ env.REP_NAME }}-test:${{ env.RELEASE }}_${{ env.SHORT_REF_NAME }}_${{ env.SHORT_SHA }} 
         
 
-  # notify-telegram:
-  #   name: Notifier
-  #   runs-on: self-hosted
-  #   if: always()
-  #   needs: [build-image, linter]
-  #   steps:
+  notify-telegram:
+    name: Notifier
+    runs-on: self-hosted
+    if: always()
+    needs: [build-image, linter]
+    steps:
 
-  #     - name: Set Telegram Message
-  #       uses: haya14busa/action-cond@v1
-  #       id: telegram_message
-  #       with:
-  #         cond: ${{ contains(join(needs.*.result, ','), 'success') }}
-  #         if_true: |
-  #           👷 ${{ github.actor }} created deploy tag.
+      - name: Set Telegram Message
+        uses: haya14busa/action-cond@v1
+        id: telegram_message
+        with:
+          cond: ${{ contains(join(needs.*.result, ','), 'success') }}
+          if_true: |
+            👷 ${{ github.actor }} created deploy tag.
             
-  #           Image assembly has been completed ✅
+            Image assembly has been completed ✅
             
-  #           ▶️ Docker Registry: ${{ secrets.CR_DH_USERNAME }}/${{ needs.build-image.outputs.REP_NAME }}
-  #           🔗 docker pull docker.io/${{ secrets.CR_DH_USERNAME }}/${{ needs.build-image.outputs.REP_NAME }}:${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
-  #           ▶️ GitHub Registry: ghcr.io/${{ github.repository_owner }}/${{ needs.build-image.outputs.REP_NAME }}
-  #           🔗 docker pull ghcr.io/${{ github.repository_owner }}/${{ needs.build-image.outputs.REP_NAME }}:${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
+            ▶️ Docker Registry: ${{ secrets.CR_DH_USERNAME }}/${{ needs.build-image.outputs.REP_NAME }}
+            🔗 docker pull docker.io/${{ secrets.CR_DH_USERNAME }}/${{ needs.build-image.outputs.REP_NAME }}:${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
+            ▶️ GitHub Registry: ghcr.io/${{ github.repository_owner }}/${{ needs.build-image.outputs.REP_NAME }}
+            🔗 docker pull ghcr.io/${{ github.repository_owner }}/${{ needs.build-image.outputs.REP_NAME }}:${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
 
-  #           🔵 Image Name: ${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
+            🔵 Image Name: ${{ needs.build-image.outputs.RELEASE }}_${{ needs.build-image.outputs.SHORT_REF_NAME }}_${{ needs.build-image.outputs.SHORT_SHA }}
 
-  #           ESLinter Check Status: ${{ needs.linter.outputs.LINTER_CHECK }}
+            ESLinter Check Status: ${{ needs.linter.outputs.LINTER_CHECK }}
 
-  #           Repository: ${{ github.repository }}  
-  #           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-  #         if_false: |
-  #           👷 ${{ github.actor }} created deploy tag.
+            Repository: ${{ github.repository }}  
+            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
+          if_false: |
+            👷 ${{ github.actor }} created deploy tag.
             
-  #           ❌Build Failed
+            ❌Build Failed
 
-  #           ESLinter Check Status: ${{ needs.linter.outputs.LINTER_CHECK }}
+            ESLinter Check Status: ${{ needs.linter.outputs.LINTER_CHECK }}
             
-  #           Repository: ${{ github.repository }}  
+            Repository: ${{ github.repository }}  
     
-  #     - name: Send to Telegram
-  #       uses: appleboy/telegram-action@master
-  #       with:
-  #         to: ${{ secrets.TG_NOTIFICATION_BOT_ID }}
-  #         token: ${{ secrets.TG_NOTIFICATION_BOT_TOKEN }}
-  #         message: ${{ steps.telegram_message.outputs.value }}
+      - name: Send to Telegram
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TG_NOTIFICATION_BOT_ID }}
+          token: ${{ secrets.TG_NOTIFICATION_BOT_TOKEN }}
+          message: ${{ steps.telegram_message.outputs.value }}
